name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add MPI
      run: export PATH=$PATH:/usr/lib64/openmpi/bin && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/openmpi/bin

    - name: Build
      run: ./build.sh

    - name: Run tests
      working-directory: ./build
      run: ./test_multiplication
