name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      
    - name: Build
      run: ./build.sh

    - name: Run main
      working-directory: ./build
      run: ./main

    - name: Run tests
      working-directory: ./build
      run: ./test_multiplication
