name: Test and container building

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MPI for running tests in action
      uses: mpi4py/setup-mpi@v1
      
    - name: Build
      run: ./build.sh

    - name: Run tests
      working-directory: ./build
      run: ./test_multiplication

    - name: Install Singularity
      run: |
        sudo apt-get update && \
        sudo apt-get install -y build-essential \
        libseccomp-dev pkg-config squashfs-tools cryptsetup
        export VERSION=1.13.15 OS=linux ARCH=amd64
        wget -O /tmp/go${VERSION}.${OS}-${ARCH}.tar.gz https://dl.google.com/go/go${VERSION}.${OS}-${ARCH}.tar.gz
        sudo tar -C /usr/local -xzf /tmp/go${VERSION}.${OS}-${ARCH}.tar.gz
        echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
        echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
        source ~/.bashrc
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
        sh -s -- -b $(go env GOPATH)/bin v1.21.0
        mkdir -p ${GOPATH}/src/github.com/sylabs
        cd ${GOPATH}/src/github.com/sylabs
        git clone https://github.com/sylabs/singularity.git
        cd singularity
        git checkout v3.6.3
        cd ${GOPATH}/src/github.com/sylabs/singularity
        ./mconfig
        cd ./builddir
        make
        sudo make install
        singularity version
        
    - name: Build container
      run: sudo singularity build container.sif container.def
