name: Test and container building

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MPI for running tests in action
      uses: mpi4py/setup-mpi@v1
      
    - name: Build
      run: ./build.sh

    - name: Run tests
      working-directory: ./build
      run: ./test_multiplication

    - name: Install singularity dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        build-essential \
        libssl-dev \
        uuid-dev \
        libgpgme11-dev \
        squashfs-tools \
        libseccomp-dev \
        pkg-config

    - name: Install Go
      run: |
        export VERSION=1.11 OS=linux ARCH=amd64 && \
        wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
        sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
        rm go$VERSION.$OS-$ARCH.tar.gz
        echo 'export GOPATH=${HOME}/go' >> ~/.bashrc && \
        echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc && \
        source ~/.bashrc
        go install github.com/golang/dep/cmd/dep@latest
        
    - name: Install singularity
      run: |
        export VERSION=3.0.3 && # adjust this as necessary \
        wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
        rpmbuild -tb singularity-${VERSION}.tar.gz && \
        sudo rpm -ivh ~/rpmbuild/RPMS/x86_64/singularity-$VERSION-1.el7.x86_64.rpm && \
        rm -rf ~/rpmbuild singularity-$VERSION*.tar.gz
        rpmbuild -tb --define='_localstatedir /mnt' singularity-$VERSION.tar.gz

    - name: Build container
      run: singularity build container.sif container.def
