name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download OpenMPI
      run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
    
    - name: Extract OpenMPI
      run: tar -xvf ./openmpi-4.0.2.tar.gz

    - name: Configure OpenMPI
      run: ./openmpi-4.0.2/configure --prefix="/home/${USER}/.openmpi"

    - name: Install OpenMPI
      run: |
        make -j
        sudo make install
      
    - name: Build
      run: ./build.sh

    - name: Run tests
      working-directory: ./build
      run: ./test_multiplication
