name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MPI for running tests in action
      uses: mpi4py/setup-mpi@v1
      
    - name: Build
      run: ./build.sh

    - name: Run tests
      working-directory: ./build
      run: ./test_multiplication

    - name: Install singularity
      run: |
        sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list && \
        sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9 && \
        sudo apt-get update && \
        sudo apt-get install -y singularity-container

    - name: Build container
      run: singularity build container.sif container.def
