name: Test and container building

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive  

    - name: Setup MPI for running tests in action
      uses: mpi4py/setup-mpi@v1
      
    - name: Build
      run: ./build.sh

    - name: Run tests
      working-directory: ./build
      run: ./test_multiplication

    - name: Setup singularity
      uses: eWaterCycle/setup-singularity@v7          
      
    - name: Build container
      run: sudo singularity build container.sif container.def    

    - name: Push container to cluster
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.CLUSTER_HOST }}
        username: ${{ secrets.CLUSTER_USERNAME }}
        password: ${{ secrets.CLUSTER_PASSWORD }}
        source: "container.sif"
        target: "~"
        
    - name: Push SLURM job file to cluster
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.CLUSTER_HOST }}
        username: ${{ secrets.CLUSTER_USERNAME }}
        password: ${{ secrets.CLUSTER_PASSWORD }}
        source: "job.sh"
        target: "~"

    - name: Start job
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.CLUSTER_HOST }}
        username: ${{ secrets.CLUSTER_USERNAME }}
        password: ${{ secrets.CLUSTER_PASSWORD }}
        script: |
          rm output.txt
          rm error.txt
          sbatch job.sh
          sleep 5
          echo "================================="
          echo "Output"
          echo "================================="
          cat output.txt
          echo "================================="
          echo "Errors"
          echo "================================="
          cat error.txt
    
